different logo image for display social media
code-orange/code-orange.nl pull request #7
Opened 2018-02-23 11:17 UTC by diederusticus

2018-02-23 13:27 UTC, timvdalen requested changes

2018-02-23 13:27 UTC, timvdalen commented on vacancies/software-developer.html
> +		<meta property="og:image" content="https://code-orange.nl/img/logo.svg>
Missing `"`

2018-02-23 13:27 UTC, timvdalen commented on vacancies/adidas-developer.html
> +		<meta property="og:image" content="https://code-orange.nl/img/logo.svg">
I don't think SVG content is supported for `og:image`, images are supposed to be a certain fixed size as well.

2018-03-09 09:23 UTC, timvdalen requested changes

2018-03-09 09:23 UTC, timvdalen commented on vacancies/adidas-developer.html
> +		<meta property="og:image" content="https://code-orange.nl/img/logo_fb.svg">
Het is een png, deze URL doet het niet

2018-03-09 09:23 UTC, timvdalen commented on vacancies/ai-lead.html
> +		<meta property="og:image" content="https://code-orange.nl/img/logo_fb.svg">
Same

2018-03-12 11:05 UTC, diederusticus commented
Fixed it!

2018-03-12 12:29 UTC, timvdalen approved these changes

2018-03-12 12:29 UTC, merged